### ISSUE TITLE
Suggest a new icon for this app

### ISSUE THREAD

**Issue by BurraAbhishek** [BurraAbhishek/SpeechVision#1]
This project currently uses the Flutter logo. This may be considered misleading to some users, especially when we are releasing our app.

We would like to have a unique icon for this app that describes this app on its own: an app which uses Artificial Intelligence technologies to help the blind and visually impaired community perceive their surroundings more independently

Once you find a suitable icon, please follow the [contributing guidelines](https://github.com/BurraAbhishek/SpeechVision/blob/main/CONTRIBUTING.md)

Alternatively, you can post the link of the icon here. All icons posted here will be thoroughly researched before approval.

**Comment by ishakmohmed** [comment]
![Copy of dont delete IT CLUB](https://user-images.githubusercontent.com/52876913/114278077-927aee80-9a60-11eb-8a41-d8526adc7ee0.png)

I hope this icon idea helps!

**Comment by BurraAbhishek** [comment]
Yeah, it's cool!

**Comment by BurraAbhishek** [comment]
![app_icon_2](https://user-images.githubusercontent.com/76472381/114666888-6ee3cc80-9d1c-11eb-92a7-549b3df7d57c.png)

This one is with the background removed...

**Comment by BurraAbhishek** [comment]
The icon will soon be added across the app...
Thanks a lot!

**Comment by BurraAbhishek** [comment]
The icon has been added to the app. Feel free to reopen with more details if you want any more changes.

**Comment by BurraAbhishek** [comment]
The icon added three months ago has served us well, but it was not truly our app icon. We always wanted something unique and distinctive for SpeechVision.

I made this icon which apparently satisfies all of the above conditions. The use of artificial intelligence is more suitably described in this icon. It's a face on a microphone which wears headphones to hear whatever the artificial eyes describe.
 
![app_icon](https://user-images.githubusercontent.com/76472381/125808627-4d9756f1-b59a-4209-8c64-ebfe726bbc7f.png)
